worker_processes 1;

events {
    worker_connections 1024;
}

http {
    sendfile on;

    upstream catalog_service {
        server catalog-service:3001;
    }

    upstream order_service {
        server order-service:3002;
    }

    upstream query_service {
        server query-service:3004;
    }

    server {
        listen 80;

        # Catalog Service REST Routes
        location /catalog/ {
            rewrite ^/catalog/(.*) /$1 break;
            proxy_pass http://catalog_service;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        # Order Service REST Routes
        location /order/ {
            rewrite ^/order/(.*) /$1 break;
            proxy_pass http://order_service;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        # GraphQL Query Service Routes
        location /graphql {
            proxy_pass http://query_service;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}